# Generated by Django 5.0.7 on 2024-08-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicalreader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalReader',
        ),
    ]
