# Generated by Django 5.0.7 on 2024-08-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_borrowed',
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrowed_by',
        ),
        migrations.AddField(
            model_name='book',
            name='borrowed_by',
            field=models.ManyToManyField(blank=True, related_name='borrowed_books', to='users.reader'),
        ),
    ]
